
# Config file for Air (https://github.com/cosmtrek/air)

# The root directory to watch for changes.
root = "."
# The directory where the binary will be built.
tmp_dir = "tmp"


[build]
  cmd = "go build -o tmp/media-manager.exe ./cmd/media-manager/main.go"
  bin = "tmp/media-manager.exe"
  full_bin = "tmp/media-manager.exe ./media"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "media", "bin", "thumbnails", "tmp"]
  delay = 1000

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true