# Config file for Air (https://github.com/cosmtrek/air)

# The root directory to watch for changes.
root = "."
# The directory where the binary will be built.
tmp_dir = "tmp"

[build]
  # Clear thumbnail cache and build (ensures uniform 200x200 thumbnails after generation changes)
  cmd = "echo 'Clearing thumbnail cache...' && rm -rf ~/.media-manager/thumbnails/* ./thumbnails/* 2>/dev/null || true && go build -o ./tmp/media-manager ./cmd/media-manager/main.go"
  # The path to the binary to run.
  bin = "tmp/media-manager"
  # The command that will be executed to run the binary.
  full_bin = "APP_ENV=dev ./tmp/media-manager ./media 2>&1 | tee tmp/dev.log"

  # File extensions to watch.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Directories to exclude from watching.
  exclude_dir = ["vendor", "media", "bin", "thumbnails", "tmp"]
  # Delay in milliseconds before rebuilding.
  delay = 1000
  # Stop the application on a build error.
  stop_on_error = true

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true