services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
    volumes:
      - ./gluetun:/gluetun

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - USER=
      - PASS=
    volumes:
      - ./transmission-config:/config
      - /mnt/media/Movies:/downloads/movies
      - /mnt/media/Series:/downloads/series
    depends_on:
      - gluetun
