#!/bin/bash
# Jellyfin Quick Setup Script for Josh's Media Center
# Run this after Jellyfin first starts

echo "🎬 Jellyfin Setup for Media Center"
echo "===================================="
echo ""
echo "Jellyfin is running at: http://192.168.1.49:8096"
echo ""
echo "FIRST TIME SETUP STEPS:"
echo ""
echo "1. Open http://192.168.1.49:8096 in your browser"
echo "2. Follow the startup wizard:"
echo "   - Create admin user (use same credentials as media-manager)"
echo "   - Add Media Libraries:"
echo "     • Movies: /mnt/media/Movies"
echo "     • TV Shows: /mnt/media/Series"
echo "   - Set language: English"
echo "   • Enable subtitle downloading (OpenSubtitles)"
echo ""
echo "3. IMPORTANT SETTINGS:"
echo "   Dashboard → Playback → Transcoding:"
echo "   • Enable hardware acceleration: AMD AMF"
echo "   • Enable all codecs (H264, HEVC, VP9, AV1)"
echo ""
echo "4. NVIDIA SHIELD SETUP:"
echo "   • Install 'Jellyfin for Android TV' from Play Store"
echo "   • Enter server: http://192.168.1.49:8096"
echo "   • Login with your credentials"
echo ""
echo "5. REMOTE ACCESS (Phase 2):"
echo "   • Configure Cloudflare tunnel"
echo "   • Set up reverse proxy"
echo "   • Create friend accounts"
echo ""
echo "📱 CLIENT APPS FOR FRIENDS:"
echo "   • Android TV: Jellyfin (Play Store)"
echo "   • Roku: Jellyfin Channel"
echo "   • Apple TV: Jellyfin (App Store)"
echo "   • iPhone/iPad: Jellyfin (App Store)"
echo "   • Web: media.yourdomain.com"
echo ""
echo "🦞 Why not Zoidberg? HOORAY!"
